# Generated by Django 5.1.4 on 2025-02-01 03:47

import django.db.models.deletion
import django.utils.timezone
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('court_type', models.CharField(blank=True, choices=[('FULL_COVERED', 'Full Covered Court'), ('HALF_COVERED', 'Half Covered Court'), ('FULL_OPEN', 'Full Open Court'), ('HALF_OPEN', 'Half Open Court'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('description', models.CharField(blank=True, choices=[('BASKETBALL', 'Basketball'), ('VOLLEYBALL', 'Volleyball'), ('TENNIS', 'Tennis'), ('BADMINTON', 'Badminton'), ('FUTSAL', 'Futsal'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courts/')),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=myapp.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='courts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Court',
                'verbose_name_plural': 'Courts',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('court_status', models.CharField(choices=[('UNUSED', 'Unused'), ('ONGOING', 'Ongoing'), ('DONE', 'Done')], default='UNUSED', max_length=10)),
                ('reservation_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='myapp.court')),
                ('user', models.ForeignKey(default=myapp.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('downpayment', models.FloatField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('PARTIAL', 'Partially Paid'), ('FULL', 'Fully Paid')], default='PARTIAL', max_length=10)),
                ('court_status', models.CharField(choices=[('UNUSED', 'Unused'), ('ONGOING', 'Ongoing'), ('DONE', 'Done')], default='UNUSED', max_length=10)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_status', to='myapp.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation Status',
                'verbose_name_plural': 'Reservation Statuses',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('user', models.ForeignKey(default=myapp.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='myapp.team'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'myapp_userprofile',
            },
        ),
    ]
