# Generated by Django 5.1.4 on 2025-01-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='court_type',
            field=models.CharField(blank=True, choices=[('basketball', 'Basketball'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courts/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
