# Generated by Django 5.1.4 on 2025-01-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_court_capacity_court_court_type_court_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'verbose_name': 'Court', 'verbose_name_plural': 'Courts'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_officer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_regular_user',
        ),
        migrations.AddField(
            model_name='court',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Officer', 'Officer'), ('User', 'User')], default='User', max_length=10),
        ),
    ]
