# Generated by Django 5.1.4 on 2025-01-27 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_court_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='myapp.team'),
        ),
    ]
