# Generated by Django 5.1.4 on 2025-01-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_court_capacity_alter_court_court_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='court_type',
            field=models.CharField(blank=True, choices=[('FULL_COVERED', 'Full Covered Court'), ('HALF_COVERED', 'Half Covered Court'), ('FULL_OPEN', 'Full Open Court'), ('HALF_OPEN', 'Half Open Court'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='description',
            field=models.CharField(blank=True, choices=[('BASKETBALL', 'Basketball'), ('VOLLEYBALL', 'Volleyball'), ('TENNIS', 'Tennis'), ('BADMINTON', 'Badminton'), ('FUTSAL', 'Futsal'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
