# Generated by Django 5.1.4 on 2025-01-31 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_userprofile_options_remove_userprofile_role_and_more'),
        ('myapp', '0008_create_user_profiles'),
    ]

    operations = [
    ]
