# Generated by Django 5.1.4 on 2025-01-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_court_user_payment_user_reservation_user_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='court_status',
            field=models.CharField(choices=[('UNUSED', 'Unused'), ('ONGOING', 'Ongoing'), ('DONE', 'Done')], default='UNUSED', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PARTIAL', 'Partially Paid'), ('FULL', 'Fully Paid')], default='PARTIAL', max_length=10),
        ),
    ]
