# Generated by Django 5.1.4 on 2025-01-31 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_reservation_court_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('downpayment', models.FloatField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('PARTIAL', 'Partially Paid'), ('FULL', 'Fully Paid')], default='PARTIAL', max_length=10)),
                ('court_status', models.CharField(choices=[('UNUSED', 'Unused'), ('ONGOING', 'Ongoing'), ('DONE', 'Done')], default='UNUSED', max_length=10)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_status', to='myapp.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation Status',
                'verbose_name_plural': 'Reservation Statuses',
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
